[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "berserk>=0.14.0",
    "chess>=1.11.2",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "python-chess>=1.999",
    "requests>=2.32.5",
]
